### ISSUE TITLE
Error when Creating Files in Data Vault

### ISSUE THREAD

**Issue by mserlin** [labrad/pylabrad#249]
I just started using labrad and am running into an issue whenever trying to create a new file in data vault. 

Labrad and data vault open and connect fine. Data vault says it is now serving. From a python script, pylabrad imports without issue and there's no problem creating a connection. Data vault, manager, and registry severs all appear as expected. 

However, when trying to create a new file in data vault, the following error appears: exception.AttributeError: 'Signal' object has no attribute 'parent' 

I've tried using multiple versions of labrad (tried scalabrad 0.5.0, 0.5.3, and 0.6.2). I tried using different versions of data vault (from the martinis group servers page, as well as copying files from other local machines that seem to work fine). It doesn't seem to be an issue related to the pylabrad version, as another computer in the lab worked with both pylabrad 0.95.2 and 0.93.2. 

This problem affects two computers in our lab and we're unsure what the cause of the problem is.

**Comment by DanielSank** [comment]
Please post an exact console dump of what you type in and the exact, complete error traceback.

**Comment by mserlin** [comment]
Thank you for your prompt response. Please let me know if there's anything else I can provide. 

>>> import labrad
>>> cxn = labrad.connect()
Enter LabRAD password (localhost:7682):
>>> cxn
LabRAD Client: 'Python Client (marec-pc)' on localhost:None

Available servers:
    data_vault
    manager
    registry
>>> cxn.data_vault.new('W',['x','v'],['y','v'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Marec\Anaconda3\envs\Python27\lib\site-packages\labrad\client.p
y", line 67, in __call__
    return f.result() if wait else f
  File "C:\Users\Marec\Anaconda3\envs\Python27\lib\site-packages\labrad\concurre
nt.py", line 100, in result
    self._result = super(MutableFuture, self).result(timeout)
  File "C:\Users\Marec\Anaconda3\envs\Python27\lib\site-packages\concurrent\futu
res\_base.py", line 405, in result
    return self.__get_result()
  File "C:\Users\Marec\Anaconda3\envs\Python27\lib\site-packages\concurrent\futu
res\_base.py", line 357, in __get_result
    raise type(self._exception), self._exception, self._traceback
labrad.types.Error: (0) [Data Vault] Remote Traceback (most recent call last):
  File "C:\Users\Marec\Anaconda3\envs\Python27\lib\site-packages\labrad\server.p
y", line 232, in request_handler
    result = yield setting.handleRequest(self, c.data, flat_data)
  File "C:\Users\Marec\Anaconda3\envs\Python27\lib\site-packages\labrad\decorato
rs.py", line 182, in handleRequest
    return self.func(server, c, *data)
  File "C:\Labrad\datavault\server.py", line 166, in new
    dataset = session.newDataset(name or 'untitled', independents, dependents)
  File "C:\Labrad\datavault\__init__.py", line 243, in newDataset
    self.hub.onNewDataset(name, self.listeners)
  File "C:\Users\Marec\Anaconda3\envs\Python27\lib\site-packages\labrad\server.p
y", line 60, in __call__
    cxn = self.parent._cxn
exceptions.AttributeError: 'Signal' object has no attribute 'parent'
 [payload=None]

**Comment by DanielSank** [comment]
This may be related to a very recent change. See #244.

**Comment by mserlin** [comment]
I saw that post, but I assumed that changing to previous versions of labrad and/or data vault would have avoided that issue. Has the problem raised in #244 only been observed on some, but not all computers? 

I'll try to implement the proposed fix a try and see what happens.

**Comment by maffoo** [comment]
Yes, this is the same problem as #244. I have created a PR #245 to fix it, just needs a review. @mserlin, if you would like to try out the u/maffoo/setting-fix and then comment on that PR if it works for you, that would be great. Otherwise, you should be able to downgrade pylabrad to version 0.95.1 and use that until we have pushed out a fix. Note that you need to switch pylabrad versions on the computer that is running the data vault server.

**Comment by maffoo** [comment]
@mserlin, this should now be fixed in master (if you're running pylabrad from source) and in version 0.95.3 on PyPI (if you're installing a pylabrad package). Can you give it a try and update this issue?

Also, just out of curiosity, are you running pylabrad from source or installing a package? I'd like to encourage people to install release versions, but I'm curious what people are doing currently.

**Comment by mserlin** [comment]
@DanielSank @maffoo, upgrading to version 0.95.3 fixed the problem. Thank you! If anything else pops up, I'll be sure to post it. 

I am installing a package and I believe so are the rest of the people in my group.
